# -*- coding: utf-8 -*-
"""car_sale_analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WDs58QV7FDOQj7muhbUQFnb6RXJOAbF1
"""

import pandas as pd
import sys
import os

file_path = sys.argv[1]
df = pd.read_csv('data_preprocessed.csv')

if 'Price_Category_Medium' in df.columns:
    medium_count = df['Price_Category_Medium'].sum()
    total = len(df)

    with open("insight1.txt", "w") as f:
        f.write(f"{medium_count} out of {total} cars fall into the medium price category")

if 'Mileage' in df.columns and 'Price' in df.columns:
    corr = df['Mileage'].corr(df['Price'])

    with open("insight2.txt", "w") as f:
        f.write(f"There is a correlation of {corr:.2f} between mileage and price (higher mileage usually reduces price)")

if 'Year' in df.columns and 'Price' in df.columns:
    corr_year = df['Year'].corr(df['Price'])

    with open("insight3.txt", "w") as f:
        f.write(f"There is a correlation of {corr_year:.2f} between car year and price (newer cars tend to be more expensive)")

body_cols = [col for col in df.columns if "Body_" in col]

if body_cols:
    body_counts = df[body_cols].sum()
    top_body = body_counts.idxmax()

    with open("insight4.txt", "w") as f:
        f.write(f"The most common car body type is {top_body.replace('Body_', '')}")

engine_cols = [col for col in df.columns if "Engine Type" in col]

if engine_cols:
    engine_counts = df[engine_cols].sum()
    top_engine = engine_counts.idxmax()

    with open("insight5.txt", "w") as f:
        f.write(f"The most common engine type is {top_engine.replace('Engine Type_', '')}")

print("Analytics completed successfully!")
os.system("python visualize.py data_preprocessed.csv")

