# -*- coding: utf-8 -*-
"""car_sales_clustring.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T2_FBSJaQir9KioKfD9rB5xCDAqDIdqp
"""

import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import sys

if len(sys.argv) < 2:
    print("Usage: python cluster.py <csv_path>")
    sys.exit(1)

file_path = sys.argv[1]
df = pd.read_csv(file_path)

features = ['Price', 'Mileage', 'EngineV', 'Year']

existing_features = [col for col in features if col in df.columns]

X = df[existing_features]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

kmeans = KMeans(n_clusters=3, random_state=42)

df['Cluster'] = kmeans.fit_predict(X_scaled)

cluster_counts = df['Cluster'].value_counts().sort_index()
print(cluster_counts)

print(df.groupby("Cluster")[["Price", "Mileage", "Year"]].mean())

df.to_csv("clustered_data.csv", index=False)

with open("clusters.txt", "w") as f:
    for cluster, count in cluster_counts.items():
        f.write(f"Cluster {cluster}: {count} samples\n")

print("Clustering completed successfully!")

