# -*- coding: utf-8 -*-
"""car_sales-preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dlKtd5tl3BOkoypk-P8MSXG3pPXzwRm_
"""

import pandas as pd

df = pd.read_csv('Car_sales.csv')
print(df.head())

df.drop('Model', axis=1, inplace=True)
print(df.head())

import pandas as pd

df = pd.read_csv("Car_sales.csv")

df.replace("NA", pd.NA, inplace=True)

df = df.apply(lambda x: x.fillna(x.mean()) if x.dtype != "object" else x.fillna(x.mode()[0]))

df["Brand"] = df["Brand"].str.replace(r"-NA", "", regex=True).str.strip()

df.drop_duplicates(inplace=True)
print(df.head())

import pandas as pd

df = pd.read_csv("Car_sales.csv")
df.replace("NA", pd.NA, inplace=True)
df = df.apply(lambda x: x.fillna(x.mean()) if x.dtype != "object" else x.fillna(x.mode()[0]))
df["Brand"] = df["Brand"].str.replace(r"-NA", "", regex=True).str.strip()
df.drop_duplicates(inplace=True)

df.drop('Model', axis=1, inplace=True)

df['Price_Category'] = pd.cut(df['Price'], bins=3, labels=['Low', 'Medium', 'High'])

df['Registration'] = df['Registration'].astype(str).str.lower().map({'yes': 1, 'no': 0})

categorical_cols = ['Brand', 'Body', 'Engine Type', 'Price_Category']
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)
print(df.head())

from sklearn.preprocessing import StandardScaler

columns_to_scale = ['Price', 'Mileage', 'EngineV', 'Year']

scaler = StandardScaler()
df[columns_to_scale] = scaler.fit_transform(df[columns_to_scale])
print(df.head())